server:
  port: 3702
spring:
  jpa: 
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/mangapp
    username: postgres
    password: admin